general {
    hide_cursor = false
    immediate_render = true
    fail_timeout = 3000
    unlock_deceleration_ms = 800
    unlock_transition_ms = 1000
    failure_halo = true
    failure_halo_size = 72
    failure_halo_opacity = 18
    failure_halo_transition_ms = 450
}

auth {
    pam {
        enabled = true
        module = hyprlock
    }
}

animations {
    enabled = true
    bezier = lockTrace, 0.2, 0.0, 0.0, 1.0
    animation = inputFieldFade, 1, 12, lockTrace
    animation = inputFieldDots, 1, 10, lockTrace
    animation = inputFieldColors, 1, 10, lockTrace
}

observatory {
    monitor =
    fps = 30
    day_seconds = 1800
    lightning_brightness = 5.0
    aurora_brightness = 1000.0
    zindex = -1
}

input-field {
    monitor =
    size = 720, 120
    outline_thickness = 0
    dots_size = 0.25
    dots_aspect_ratio = 1.75
    dots_spacing = 0.28
    dots_center = true
    dots_rounding = 3
    dots_text_format =
    outer_color = rgba(00000000)
    inner_color = rgba(00000000)
    font_color = rgba(66e0ffff)
    fade_on_empty = true
    fade_timeout = 3000
    placeholder_text =
    check_color = rgba(eeffffff)
    fail_color = rgba(ff6644ff)
    fail_text = <span letter_spacing="2200">ACCESS DENIED</span>
    font_family = Orbitron
    font_size = 30
    hide_input = false
    swap_font_color = true
    rounding = 0
    position = 0, -150
    halign = center
    valign = center
    zindex = 0
}
